Solve problem with error output.

diff --git a/bin/dirtree2md b/bin/dirtree2md
--- a/bin/dirtree2md
+++ b/bin/dirtree2md
@@ -14,7 +14,7 @@ function parse_path() {
 }
 
 function error() {
-	echo "ERROR: $1"
+	echo "ERROR: $1" 1>&2
 	exit $2
 }
 
@@ -81,12 +81,10 @@ function main() {
 				DOCTITLE_TOOL="$OPTARG"
 			;;
 			\?)
-				echo "ERROR: Invalid option: -$OPTARG"
-				exit 1
+				error "Invalid option: -$OPTARG" 1
 			;;
 			\:)
-				echo "ERROR: Option -$OPTARG requires an argument."
-				exit 1
+				error "ERROR: Option -$OPTARG requires an argument." 1
 			;;
 		esac
 	done
